FROM amd64/python:3.12-bookworm

WORKDIR /code
VOLUME /code/docker_output
#setup requirements
RUN apt update -y && apt install -y binutils

COPY . /code

RUN pip install --disable-pip-version-check --no-cache-dir -U wheel pip
RUN pip install --disable-pip-version-check --no-cache-dir -r requirements.txt -r buildrequirements.txt

CMD ["sh", "-c", "python build.py -c -r -z --docker"]
