FROM tobix/pywine:3.12

WORKDIR ./
VOLUME /docker_output
#setup requirements
RUN apt update -y

#setup binutils for PyInstaller
RUN apt install -y binutils

COPY requirements.txt ./
COPY buildrequirements.txt ./

RUN pip install --disable-pip-version-check --no-cache-dir -U setuptools wheel pip
RUN pip install --disable-pip-version-check --no-cache-dir -r requirements.txt
RUN pip install --disable-pip-version-check --no-cache-dir -r buildrequirements.txt

COPY . .
CMD ["wine", "python", "./build.py", "-c", "-r", "-z", "--docker"]
