FROM tobix/pywine:3.12

ENV WINEARCH=win64
WORKDIR /code
VOLUME /code/docker_output

COPY . /code

RUN wine python -m pip install --disable-pip-version-check --no-cache-dir -U wheel pip
RUN wine python -m pip install --disable-pip-version-check --no-cache-dir -r requirements.txt -r buildrequirements.txt


CMD ["sh", "-c", "wine python build.py -c -r -z --docker"]
