{
    "loc_version": "v007",
    "language_name": "ภาษาไทย",
    "language_short": "th",
    
    
    "window_main_title": "ระบบดาวน์โหลดอัปเดตเกม PS3",
    "window_main_titleid_label": "กรุณาใส่รหัส TitleID",
    "window_main_enter_btn": "ค้นหา",
    "window_main_progress_label": "กำลังโหลดไฟล์ {0}:\n{1}/{2}({3}%)\nความเร็วในการดาวน์โหลด: {4}",
    "window_main_config_btn": "การกำหนดค่า",
    "window_main_exit_btn": "ออก",
    "window_main_queue_btn": "คิว",
    
    "window_config_title": "การกำหนดค่า",
    "window_config_dldir_label": "ตำแหน่งการดาวน์โหลด:",
    "window_config_verify_label": "ยืนยันไฟล์:",
    "window_config_checkIfAlreadyDownloaded_label": "ตรวจสอบไฟล์ที่ถูกดาวน์โหลดแล้ว:",
    "window_config_checkForNewRelease_label": "ตรวบจสอบเนื้อหาใหม่ขณะกำลังเริ่มต้น:",
    "window_config_storageThreshold_label": "เกณฑ์การจัดเก็บ (ในรูปแบบ %):",
    "window_config_currentLoc_label": "ภาษา:",
    "window_config_useproxy_label": "ใช้งานพร็อกซี่เซิฟเวอร์ใหม่ไม่? (สำหรับ SOCKS5 เท่านั้น!)",
    "window_config_proxyip_label": "พร็อกซี่ IP:",
    "window_config_proxyport_label": "พร็อกซี่ Port:",
    "window_config_proxyuser_laber": "พร็อกซี่ชื่อผู้ใช้:",
    "window_config_proxypass_label": "พร็อกซี่รหัสผ่าน",
    "window_config_cancel_btn": "ยกเลิก",
    "window_config_save_btn": "บันทึก",
    
    "window_select_title": "เลือกการอัปเดต",
    "window_select_text_label": "เกม: {0}\tรหัสเกม: {1}",
    "window_select_table_ver": "เวอร์ชั่น",
    "window_select_table_size": "ขนาดไฟล์",
    "window_select_table_sysver": "PS3 เวอร์ชั่นเฟิร์มแวร์",
    "window_select_download_btn": "ดาวน์โหลด",
    "window_select_cancel_btn": "ยกเลิก",
    "window_select_queue_btn": "เพิ่มเข้าคิวดาวน์โหลด",
    "window_select_help_label": "กดปุ่ม Ctrl ค้างและคลิกการอัปเดตที่คุณต้องการเลือก",
    
    "window_relNotify_title": "พบเนื้อหาใหม่!",
    "window_relNotify_version_label": "เวอร์ชั่นปัจจุบัน: {0}\nNew version: {1}",
    "window_relNotify_changelog_label": "การเปลี่ยนแปลง:",
    "window_relNotify_web_btn": "เปิดในเว็บเบราว์เซอร์",
    "window_relNotify_dl_btn": "ดาวน์โหลดและติดตั้งอัปเดต",
    "window_relNotify_close_btn": "ปิด",
    
    "window_queue_title": "คิดการดาวน์โหลด",
    "window_queue_table_num": "เลขที่",
    "window_queue_table_game": "เกม",
    "window_queue_table_titleid": "รหัสเกม",
    "window_queue_table_ver": "เวอร์ชั่น",
    "window_queue_table_size": "ขนาดไฟล์",
    "window_queue_download_btn": "เริ่มดาวน์โหลด",
    "window_queue_close_btn": "ปิด",
    "window_queue_moveup_btn": "ย้ายขั้น",
    "window_queue_movedown_btn": "ย้ายลง",
    "window_queue_remove_btn": "ลบ",
    "window_queue_totalsize_label": "ขนาดไฟล์: {0}",
    
    "msg_configFileLoaded": "โหลดไฟล์การกำหนดค่าเรียบร้อยแล้ว!",
    "msg_noConfigFile": "ไม่พบไฟล์การกำหนดค่าใช้การตั้งค่าเดิม!",
    "msg_configFileSaved": "บันทึกการกำหนดค่าแล้วร้อยแล้ว",
    "msg_loadedTitledb": "โหลดรหัสเกม \"{0}\"",
    "msg_titleIDIs": "เกม: {0}\t รหัสเกม: {1}",
    "msg_titleIDNotValid": "รหัสเกมไม่ถูกต้องd!",
    "msg_metaNotAvailable": "ไม่พบไฟล์ Meta สำหรับรหัสเกมนี้!",
    "msg_metaNotAvailable": "ไม่พบไฟล์ Meta สำหรับรหัสเกมนี้!",
    "msg_metaFileEmpty": "ไม่พบข้อมูลที่อยู่ในไฟล์ Meta สำหรับรหัสเกมนี้!",
    "msg_startingDownloads": "เริ่มดาวน์โหลดอัปเดต",
    "msg_alreadyDownloadedNoVerify": "ไฟล์ \"{0}\" ถูกดาวน์โหลดแล้วกำลังทำการข้าม! ไฟล์ไม่ถูกยืนยัน!",
    "msg_alreadyDownloadedVerify": "ไฟล์ \"{0}\" ถูกดาวน์โหลดแล้วกำลังทำการข้าม! ยืนยันโดยการเข้ารหัส SHA-1!",
    "msg_startSingleDownload": "เริ่มการดาวน์โหลดแล้ว {0} จาก {1}",
    "msg_verifySuccess": "การยืนยันสำหรับ \"{0}\" เสร็จสิ้นแล้ว!",
    "msg_verifyFailure": "การยืนยันสำหรับ \"{0}\" ล้มเหลว!\tกำลังลบไฟล์!",
    "msg_noVerify": "ไฟล์ \"{0}\" ไม่ได้รับการยืนยัน!",
    "msg_finishedDownload": "กำลังเสร็จสิ้นการดาวน์โหลด {0} ไฟล์!",
    "msg_notEnoughDiskSpace": "พื้นที่ไม่เพียงพอ!",
    "msg_spaceBelowThreshold": "ขนาดที่ว่างมีน้อยกว่า {0}%",
    "msg_relCheckError": "ไม่สามารถตรวจสอบเนื้อหาใหม่ได้!",
    "msg_alreadyUpToDate": "เป็นเนื้อหาล่าสุดอยู่แล้ว!",
    "msg_foundNewRelease": "พบเนื้อหาใหม่ \"{0}\"",
    "msg_NoReleaseArchiveForPlatformOrArch": "ไม่สามารถค้นหาเนื้อใหม่สำหรับสถาปัตยกรรมหรือแพลตฟอร์มปัจจุบันของคุณได้. แพลตฟอร์ม(Platform): \"{0}\" สถาปัตยกรรม(Architecture): \"{1}\" การประมวลผล(Compile): \"{2}\"",
    "msg_dldirNotWriteable": "เส้นการดาวน์โหลดที่คุณได้เลือกไว้ไม่สามารถเขียนข้อมูลได้! \"{0}\"",
    "msg_checkProxySettings": "กรุณาตรวจสอบความถูกต้องของการตั้งค่าพร็อกซี่เซิฟเวอร์!"
}
